[package]
name = "day01"
version = "0.1.0"
authors = ["jomsch <jomsch@jomsch.de>"]
edition = "2018"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
anyhow = "1.0.36"
